## RDP connection details
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

version: 1.0.{build}-alpha1
branches:
  only:
  - master
image: Visual Studio 2017

environment:
  nodejs_version: "LTS"
  COVERALLS_REPO_TOKEN: "t2ICv0RcHszOpsCpakUcBH3rmOeRDWeTo"
  
clone_folder: c:\projects\NWheels
  
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  # install angular CLI
  - npm install -g @angular/cli
  
before_build:
- cmd: >-
    cd c:\projects\NWheels\Source

    dotnet --version

    dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    cd c:\projects\NWheels\Source

    dotnet publish
test_script:
- cmd: >-
    cd c:\projects\NWheels
    
    nuget install OpenCover -Version 4.6.519 -OutputDirectory Tools
    
    cd c:\projects\NWheels\Tools\OpenCover.4.6.519\tools

    OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test c:\projects\NWheels\Source\NWheels.Implementation.UnitTests\NWheels.Implementation.UnitTests.csproj" -register:user -output:MergedResult.xml -oldStyle -filter:"+[*]* -[*FluentAssertions*]* -[*]*UnitTests"

#   cd c:\projects\NWheels\Source
#
#   dotnet test NWheels.Implementation.UnitTests\NWheels.Implementation.UnitTests.csproj --logger "trx;LogFileName=test-results-1.xml"
#
#   dotnet test NWheels.Injection.Adapters.Autofac.UnitTests\NWheels.Injection.Adapters.Autofac.UnitTests.csproj --logger "trx;LogFileName=test-results-2.xml"
#
#   dotnet test NWheels.Compilation.Adapters.Roslyn.UnitTests\NWheels.Compilation.Adapters.Roslyn.UnitTests.csproj --logger "trx;LogFileName=test-results-3.xml"
#
#   dotnet test NWheels.Platform.Rest.Implementation.UnitTests\NWheels.Platform.Rest.Implementation.UnitTests.csproj --logger "trx;LogFileName=test-results-4.xml"
#
#   dotnet test NWheels.Frameworks.Ddd.Implementation.UnitTests\NWheels.Frameworks.Ddd.Implementation.UnitTests.csproj --logger "trx;LogFileName=test-results-6.xml"
#
#   dotnet test NWheels.SystemTests\NWheels.SystemTests.csproj --logger "trx;LogFileName=test-results-7.xml"
#
#   dotnet test NWheels.Platform.Messaging.Tests\NWheels.Platform.Messaging.Tests.csproj --logger "trx;LogFileName=test-results-8.xml"

#   cd c:\projects\NWheels\Source\NWheels.Samples.FirstHappyPath.HelloService.Tests\GeneratedDeployables\HelloWorldAppTests
#
#   node --version
#
#   npm --version
#   
#   npm install
#
#   node_modules\.bin\grunt e2e 

after_test:
- cmd: >-
    cd c:\projects\NWheels\Tools\OpenCover.4.6.519\tools

#   OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test c:\projects\NWheels\Source\NWheels.Implementation.UnitTests\NWheels.Implementation.UnitTests.csproj" -register:user -output:MergedResult.xml -oldStyle -filter:"+[*]* -[*FluentAssertions*]* -[*]*UnitTests"
#
#   cd c:\projects\NWheels\Source\Presentation\Web\AppVeyorPoc
#
#   node --version
# 
#   npm --version
#    
#   npm install
#    
#   ng test --single-run=true
#    
#   echo export class Configuration{static appVeyorToken = 'token';} > configuration.ts
#    
#   ng e2e
    
## Pause build until file from desktop will be removed
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))    