init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
version: 1.0.{build}-alpha1
branches:
  only:
  - master
image: Visual Studio 2017
clone_folder: c:\projects\NWheels
before_build:
- cmd: >-
    cd c:\projects\NWheels\Source

    dotnet --version

    dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    cd c:\projects\NWheels\Source

    dotnet publish
test_script:
- cmd: >-
    cd c:\projects\NWheels\Source

    dotnet test NWheels.Implementation.UnitTests\NWheels.Implementation.UnitTests.csproj --logger "trx;LogFileName=test-results-1.xml"

    dotnet test NWheels.Injection.Adapters.Autofac.UnitTests\NWheels.Injection.Adapters.Autofac.UnitTests.csproj --logger "trx;LogFileName=test-results-2.xml"

    dotnet test NWheels.Compilation.Adapters.Roslyn.UnitTests\NWheels.Compilation.Adapters.Roslyn.UnitTests.csproj --logger "trx;LogFileName=test-results-3.xml"

    dotnet test NWheels.Platform.Rest.Implementation.UnitTests\NWheels.Platform.Rest.Implementation.UnitTests.csproj --logger "trx;LogFileName=test-results-4.xml"

    dotnet test NWheels.Platform.Messaging.UnitTests\NWheels.Platform.Messaging.UnitTests.csproj --logger "trx;LogFileName=test-results-5.xml"

    dotnet test NWheels.Frameworks.Ddd.Implementation.UnitTests\NWheels.Frameworks.Ddd.Implementation.UnitTests.csproj --logger "trx;LogFileName=test-results-6.xml"

    dotnet test NWheels.SystemTests\NWheels.SystemTests.csproj --logger "trx;LogFileName=test-results-7.xml"
    
after_test:
- cmd: >-
    cd c:\projects\NWheels\Source\Presentation\Web\AppVeyorPoc

    npm --version
    
    npm test